name: Rust

on:
  push:
    branches: 
      - 'main'
  pull_request:
    branches: 
      - 'main'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    env: 
      ADVENTOFCODE_ROOT: adventofcode

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cd $ADVENTOFCODE_ROOT && cargo build --verbose
    - name: Run tests
      run: cd $ADVENTOFCODE_ROOT && cargo test --verbose

